SOURCES = util.cpp \
		  test.cpp \
		  bubble.cpp \
		  insert.cpp \
		  select.cpp \
		  shell.cpp \
		  merge.cpp \
		  quick.cpp \
		  heap.cpp

test: $(SOURCES)
	g++ -o $@ $(SOURCES)

clean:
	rm -f test

.PHONY: clean
