#!/bin/sh

# CA
openssl genrsa -out ca/ca-key.pem 1024
openssl req -new -key ca/ca-key.pem -out ca/ca-req.csr    # Email(test@xxx.com)
openssl x509 -req -in ca/ca-req.csr -signkey ca/ca-key.pem -out ca/ca-cert.pem -days 3650
openssl pkcs12 -export -clcerts -in ca/ca-cert.pem -inkey ca/ca-key.pem -out ca/ca.p12


# Server
openssl genrsa -out server/server-key.pem 1024
openssl req -new -key server/server-key.pem -out server/server-req.csr    # Email(server@xxx.com)
openssl x509 -req -in server/server-req.csr -signkey server/server-key.pem -out server/server-cert.pem -CA ca/ca-cert.pem -CAkey ca/ca-key.pem -CAcreateserial -days 3650
openssl pkcs12 -export -clcerts -in server/server-cert.pem -inkey server/server-key.pem -out server/server.p12


# Client
openssl genrsa -out client/client-key.pem 1024
openssl req -new -key client/client-key.pem -out client/client-req.csr    # Email(client@xxx.com)
openssl x509 -req -in client/client-req.csr -signkey client/client-key.pem -out client/client-cert.pem -CA ca/ca-cert.pem -CAkey ca/ca-key.pem -CAcreateserial -days 3650
openssl pkcs12 -export -clcerts -in client/client-cert.pem -inkey client/client-key.pem -out client/client.p12


# jks
keytool -import -trustcacerts -file ca/ca-cert.pem -keystore truststore.jks -storepass 654321 -alias ca -keypass 654321
